# Generated by Django 5.0 on 2024-08-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_community_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpSeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('mobile_number', models.CharField(max_length=20)),
                ('purpose', models.TextField()),
                ('payment_info', models.TextField()),
                ('help_needed', models.TextField()),
                ('raise_fund', models.BooleanField(default=False)),
            ],
        ),
    ]
